global:
  scrape_interval: 10s  # How frequently to scrape targets.

scrape_configs:
  - job_name: app
    metrics_path: /metrics
    static_configs:
      - targets:
        - alenam0161.grafana.net:9100