# @package _group_
_target_: moviescripts.models.BertSentenceClassifier_MeanSentence
# config:
#   dialations: [1, 1, 1, 1]
#   conv1_kernel_size: 5
#   bn_momentum: 0.02
# # depends on normals, color, raw_coordinates
# # varies from 3 to 9
# in_channels: ${data.in_channels}
# out_channels: ${data.num_labels}
num_labels: ${data.num_labels}
