general:
  seed: null
  checkpoint: null #saved/baseline/2023-04-23_0116/2edfc897/c308610c_a3d2/checkpoints/epoch=19-step=50000.ckpt
  freeze_backbone: false # train only last layer
  project_name: moviescripts
  workspace: alen.am0161
  experiment_name: baseline

  save_dir: saved/${general.experiment_name}/${now:%Y-%m-%d_%H%M}

  experiment_id: ??? # commit[:8], or unique from logger
  version: offline #0.1.1 # md5[:8] of config
  devices: ???
  accelerator: ???
  version_base: None

defaults:
  - model: BertEncodedClassifer
  - loss: cross_entropy
  - data: author_text
  - data/data_loaders: simple_loader
  - data/datasets: starwars_encoded
  - predict_model: bertmodel_onnx
  # - data/collation_functions: voxelize_collate
  - logging: offline
  - metrics: Accuracy
  - tokenizer: BertUncased
  - optimizer: adamw
  - scheduler: onecyclelr
  - trainer: trainer
  - callbacks: callbacks

hydra:
  run:
    dir: saved/hydra_logs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: saved/hydra_logs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    # dir: ${general.save_dir}
    subdir: ${hydra.job.num}_${hydra.job.id}
